---
jinja2_transforms:
  - name: interface_config_transform             # Unique name for your transform
    description: "interface config transform"    # (optional)
    query: "interface_config_query"              # Name or ID of the GraphQLQuery
    template_path: "interface_config.j2"         # Path to the main Jinja2 template

queries:
  - name: interface_config_query                 # Name of the GraphQLQuery
    file_path: "interface_config.gql"            # Path to the main Jinja2 template
